import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { BuildingsProvider } from "@/context/Buildings";
import { UserProvider } from "@/context/User";
import { Footer } from "@/components/Footer";
import { CityProvider } from "@/context/City";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-screen h-screen`}>
        <UserProvider>
          <CityProvider>
            <BuildingsProvider>
              <Header />
              <div
                className="w-full h-[calc(100vh_-_8rem)]"
              >
                {children}
              </div>
              <Footer />
            </BuildingsProvider>
          </CityProvider>
        </UserProvider>
      </body>
    </html>
  );
}
