import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { Header } from "@/components/Header";
import { BuildingsProvider } from "@/context/Buildings";
import { UserProvider } from "@/context/User";
import { CityProvider } from "@/context/City";
import { MapsProvider } from "@/context/Map";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <div
        className="w-full h-[calc(100vh_-_4rem)]"
      >
        {children}
      </div>
    </>

  );
}
